// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package sqlc

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (type) VALUES ($1) RETURNING id, created_at, updated_at, type
`

func (q *Queries) CreateAccount(ctx context.Context, type_ string) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, type_)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :one
DELETE FROM accounts WHERE id = $1 RETURNING id, created_at, updated_at, type
`

func (q *Queries) DeleteAccount(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, deleteAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const findAccountByID = `-- name: FindAccountByID :one
SELECT id, created_at, updated_at, type FROM accounts WHERE id = $1
`

func (q *Queries) FindAccountByID(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, findAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const findAccountByType = `-- name: FindAccountByType :one
SELECT id, created_at, updated_at, type FROM accounts WHERE type = $1
`

func (q *Queries) FindAccountByType(ctx context.Context, type_ string) (Account, error) {
	row := q.db.QueryRow(ctx, findAccountByType, type_)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, created_at, updated_at, type FROM accounts
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts SET type = $2 WHERE id = $1 RETURNING id, created_at, updated_at, type
`

type UpdateAccountParams struct {
	ID   int64  `db:"id"`
	Type string `db:"type"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount, arg.ID, arg.Type)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
	)
	return i, err
}
