// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balance.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToBalance = `-- name: AddToBalance :one
INSERT INTO balances (account_id, balance, locked_balance)
VALUES ($1, $2, $3)
ON CONFLICT (account_id) DO UPDATE
SET balance = COALESCE(balances.balance, 0) + COALESCE($4::bigint, 0),
    locked_balance = COALESCE(balances.locked_balance, 0) + COALESCE($5::bigint, 0)
RETURNING id, created_at, updated_at, account_id, balance, locked_balance
`

type AddToBalanceParams struct {
	AccountID       int64       `db:"account_id"`
	Balance         int64       `db:"balance"`
	LockedBalance   int64       `db:"locked_balance"`
	Balance_2       pgtype.Int8 `db:"balance_2"`
	LockedBalance_2 pgtype.Int8 `db:"locked_balance_2"`
}

func (q *Queries) AddToBalance(ctx context.Context, arg AddToBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, addToBalance,
		arg.AccountID,
		arg.Balance,
		arg.LockedBalance,
		arg.Balance_2,
		arg.LockedBalance_2,
	)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.Balance,
		&i.LockedBalance,
	)
	return i, err
}

const deleteBalance = `-- name: DeleteBalance :one
DELETE FROM balances WHERE account_id = $1 RETURNING id, created_at, updated_at, account_id, balance, locked_balance
`

func (q *Queries) DeleteBalance(ctx context.Context, accountID int64) (Balance, error) {
	row := q.db.QueryRow(ctx, deleteBalance, accountID)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.Balance,
		&i.LockedBalance,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT id, created_at, updated_at, account_id, balance, locked_balance FROM balances WHERE account_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, accountID int64) (Balance, error) {
	row := q.db.QueryRow(ctx, getBalance, accountID)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.Balance,
		&i.LockedBalance,
	)
	return i, err
}

const getBalances = `-- name: GetBalances :many
SELECT id, created_at, updated_at, account_id, balance, locked_balance FROM balances
`

func (q *Queries) GetBalances(ctx context.Context) ([]Balance, error) {
	rows, err := q.db.Query(ctx, getBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Balance
	for rows.Next() {
		var i Balance
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountID,
			&i.Balance,
			&i.LockedBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveBalance = `-- name: SaveBalance :one
INSERT INTO balances (account_id, balance, locked_balance)
VALUES ($1, $2, $3)
ON CONFLICT (account_id) DO UPDATE
SET balance = COALESCE($4::bigint, balances.balance),
    locked_balance = COALESCE($5::bigint, locked_balance)
RETURNING id, created_at, updated_at, account_id, balance, locked_balance
`

type SaveBalanceParams struct {
	AccountID       int64       `db:"account_id"`
	Balance         int64       `db:"balance"`
	LockedBalance   int64       `db:"locked_balance"`
	Balance_2       pgtype.Int8 `db:"balance_2"`
	LockedBalance_2 pgtype.Int8 `db:"locked_balance_2"`
}

func (q *Queries) SaveBalance(ctx context.Context, arg SaveBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, saveBalance,
		arg.AccountID,
		arg.Balance,
		arg.LockedBalance,
		arg.Balance_2,
		arg.LockedBalance_2,
	)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.Balance,
		&i.LockedBalance,
	)
	return i, err
}
