// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balance.sql

package sqlc

import (
	"context"
)

const deleteBalance = `-- name: DeleteBalance :one
DELETE FROM balances WHERE account_id = $1 RETURNING id, created_at, updated_at, account_id, balance, locked_balance
`

func (q *Queries) DeleteBalance(ctx context.Context, accountID int64) (Balance, error) {
	row := q.db.QueryRow(ctx, deleteBalance, accountID)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.Balance,
		&i.LockedBalance,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT id, created_at, updated_at, account_id, balance, locked_balance FROM balances WHERE account_id = $1
`

func (q *Queries) GetBalance(ctx context.Context, accountID int64) (Balance, error) {
	row := q.db.QueryRow(ctx, getBalance, accountID)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.Balance,
		&i.LockedBalance,
	)
	return i, err
}

const getBalances = `-- name: GetBalances :many
SELECT id, created_at, updated_at, account_id, balance, locked_balance FROM balances
`

func (q *Queries) GetBalances(ctx context.Context) ([]Balance, error) {
	rows, err := q.db.Query(ctx, getBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Balance
	for rows.Next() {
		var i Balance
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountID,
			&i.Balance,
			&i.LockedBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveBalance = `-- name: SaveBalance :one
INSERT INTO balances (account_id, balance, locked_balance)
VALUES ($1, $2, $3)
ON CONFLICT (account_id) DO UPDATE
SET balance = COALESCE(EXCLUDED.balance, balances.balance),
    locked_balance = COALESCE(EXCLUDED.locked_balance, balances.locked_balance)
RETURNING id, created_at, updated_at, account_id, balance, locked_balance
`

type SaveBalanceParams struct {
	AccountID     int64 `db:"account_id"`
	Balance       int64 `db:"balance"`
	LockedBalance int64 `db:"locked_balance"`
}

func (q *Queries) SaveBalance(ctx context.Context, arg SaveBalanceParams) (Balance, error) {
	row := q.db.QueryRow(ctx, saveBalance, arg.AccountID, arg.Balance, arg.LockedBalance)
	var i Balance
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.Balance,
		&i.LockedBalance,
	)
	return i, err
}
