// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: idempotency.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (
    key, 
    user_id, 
    resource_path, 
    request_params, 
    recovery_point
) VALUES (
    $1, $2, $3, $4, 'started'
) RETURNING id, key, user_id, resource_path, request_params, response_code, response_body, recovery_point, message, created_at
`

type CreateIdempotencyKeyParams struct {
	Key           string      `db:"key"`
	UserID        pgtype.Int8 `db:"user_id"`
	ResourcePath  string      `db:"resource_path"`
	RequestParams []byte      `db:"request_params"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.Key,
		arg.UserID,
		arg.ResourcePath,
		arg.RequestParams,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.ResourcePath,
		&i.RequestParams,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.RecoveryPoint,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_keys 
WHERE key = $1 AND user_id = $2
`

type DeleteIdempotencyKeyParams struct {
	Key    string      `db:"key"`
	UserID pgtype.Int8 `db:"user_id"`
}

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, arg DeleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, arg.Key, arg.UserID)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT id, key, user_id, resource_path, request_params, response_code, response_body, recovery_point, message, created_at FROM idempotency_keys 
WHERE key = $1 AND user_id = $2
`

type GetIdempotencyKeyParams struct {
	Key    string      `db:"key"`
	UserID pgtype.Int8 `db:"user_id"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.Key, arg.UserID)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.ResourcePath,
		&i.RequestParams,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.RecoveryPoint,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const updateIdempotencyKeyResponse = `-- name: UpdateIdempotencyKeyResponse :one
UPDATE idempotency_keys 
SET 
    response_code = $3, 
    response_body = $4, 
    message = $5,
    recovery_point = 'completed'
WHERE key = $1 AND user_id = $2
RETURNING id, key, user_id, resource_path, request_params, response_code, response_body, recovery_point, message, created_at
`

type UpdateIdempotencyKeyResponseParams struct {
	Key          string      `db:"key"`
	UserID       pgtype.Int8 `db:"user_id"`
	ResponseCode pgtype.Int4 `db:"response_code"`
	ResponseBody []byte      `db:"response_body"`
	Message      pgtype.Text `db:"message"`
}

func (q *Queries) UpdateIdempotencyKeyResponse(ctx context.Context, arg UpdateIdempotencyKeyResponseParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, updateIdempotencyKeyResponse,
		arg.Key,
		arg.UserID,
		arg.ResponseCode,
		arg.ResponseBody,
		arg.Message,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.UserID,
		&i.ResourcePath,
		&i.RequestParams,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.RecoveryPoint,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}
