// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_entries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (transaction_id, account_id, amount, direction, balance_after, locked_balance_after)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, created_at, updated_at, transaction_id, account_id, amount, direction, balance_after, locked_balance_after
`

type CreateLedgerEntryParams struct {
	TransactionID      int64  `db:"transaction_id"`
	AccountID          int64  `db:"account_id"`
	Amount             int64  `db:"amount"`
	Direction          string `db:"direction"`
	BalanceAfter       int64  `db:"balance_after"`
	LockedBalanceAfter int64  `db:"locked_balance_after"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.TransactionID,
		arg.AccountID,
		arg.Amount,
		arg.Direction,
		arg.BalanceAfter,
		arg.LockedBalanceAfter,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TransactionID,
		&i.AccountID,
		&i.Amount,
		&i.Direction,
		&i.BalanceAfter,
		&i.LockedBalanceAfter,
	)
	return i, err
}

const deleteLedgerEntry = `-- name: DeleteLedgerEntry :one
DELETE FROM ledger_entries WHERE id = $1 RETURNING id, created_at, updated_at, transaction_id, account_id, amount, direction, balance_after, locked_balance_after
`

func (q *Queries) DeleteLedgerEntry(ctx context.Context, id int64) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, deleteLedgerEntry, id)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TransactionID,
		&i.AccountID,
		&i.Amount,
		&i.Direction,
		&i.BalanceAfter,
		&i.LockedBalanceAfter,
	)
	return i, err
}

const findLedgerEntriesByAccountID = `-- name: FindLedgerEntriesByAccountID :many
SELECT le.id, le.created_at, le.updated_at, le.transaction_id, le.account_id, le.amount, le.direction, le.balance_after, le.locked_balance_after, t.reference, t.type, t.status FROM ledger_entries le
JOIN transactions t ON le.transaction_id = t.id
WHERE account_id = $1
ORDER BY t.created_at DESC
`

type FindLedgerEntriesByAccountIDRow struct {
	ID                 int64              `db:"id"`
	CreatedAt          pgtype.Timestamptz `db:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at"`
	TransactionID      int64              `db:"transaction_id"`
	AccountID          int64              `db:"account_id"`
	Amount             int64              `db:"amount"`
	Direction          string             `db:"direction"`
	BalanceAfter       int64              `db:"balance_after"`
	LockedBalanceAfter int64              `db:"locked_balance_after"`
	Reference          pgtype.Text        `db:"reference"`
	Type               string             `db:"type"`
	Status             string             `db:"status"`
}

func (q *Queries) FindLedgerEntriesByAccountID(ctx context.Context, accountID int64) ([]FindLedgerEntriesByAccountIDRow, error) {
	rows, err := q.db.Query(ctx, findLedgerEntriesByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindLedgerEntriesByAccountIDRow
	for rows.Next() {
		var i FindLedgerEntriesByAccountIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TransactionID,
			&i.AccountID,
			&i.Amount,
			&i.Direction,
			&i.BalanceAfter,
			&i.LockedBalanceAfter,
			&i.Reference,
			&i.Type,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLedgerEntriesByTransactionID = `-- name: FindLedgerEntriesByTransactionID :many
SELECT id, created_at, updated_at, transaction_id, account_id, amount, direction, balance_after, locked_balance_after FROM ledger_entries WHERE transaction_id = $1
`

func (q *Queries) FindLedgerEntriesByTransactionID(ctx context.Context, transactionID int64) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, findLedgerEntriesByTransactionID, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TransactionID,
			&i.AccountID,
			&i.Amount,
			&i.Direction,
			&i.BalanceAfter,
			&i.LockedBalanceAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLedgerEntryByID = `-- name: FindLedgerEntryByID :one
SELECT id, created_at, updated_at, transaction_id, account_id, amount, direction, balance_after, locked_balance_after FROM ledger_entries WHERE id = $1
`

func (q *Queries) FindLedgerEntryByID(ctx context.Context, id int64) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, findLedgerEntryByID, id)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TransactionID,
		&i.AccountID,
		&i.Amount,
		&i.Direction,
		&i.BalanceAfter,
		&i.LockedBalanceAfter,
	)
	return i, err
}

const listLedgerEntries = `-- name: ListLedgerEntries :many
SELECT id, created_at, updated_at, transaction_id, account_id, amount, direction, balance_after, locked_balance_after FROM ledger_entries ORDER BY created_at DESC
`

func (q *Queries) ListLedgerEntries(ctx context.Context) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TransactionID,
			&i.AccountID,
			&i.Amount,
			&i.Direction,
			&i.BalanceAfter,
			&i.LockedBalanceAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
