// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64              `db:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	Type      string             `db:"type"`
}

type Balance struct {
	ID            int64              `db:"id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at"`
	AccountID     int64              `db:"account_id"`
	Balance       int64              `db:"balance"`
	LockedBalance int64              `db:"locked_balance"`
}

type LedgerEntry struct {
	ID                 int64              `db:"id"`
	CreatedAt          pgtype.Timestamptz `db:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at"`
	TransactionID      int64              `db:"transaction_id"`
	AccountID          int64              `db:"account_id"`
	Amount             int64              `db:"amount"`
	Direction          string             `db:"direction"`
	BalanceAfter       int64              `db:"balance_after"`
	LockedBalanceAfter int64              `db:"locked_balance_after"`
}

type Transaction struct {
	ID        int64              `db:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	Reference pgtype.Text        `db:"reference"`
}

type WaitlistEntry struct {
	ID        int64              `db:"id"`
	CreatedAt pgtype.Timestamptz `db:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at"`
	DeletedAt pgtype.Timestamptz `db:"deleted_at"`
	Email     string             `db:"email"`
	FirstName string             `db:"first_name"`
	LastName  string             `db:"last_name"`
}
