// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (reference) VALUES ($1) RETURNING id, created_at, updated_at, reference
`

func (q *Queries) CreateTransaction(ctx context.Context, reference pgtype.Text) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction, reference)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Reference,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :one
DELETE FROM transactions WHERE id = $1 RETURNING id, created_at, updated_at, reference
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRow(ctx, deleteTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Reference,
	)
	return i, err
}

const findTransactionByID = `-- name: FindTransactionByID :one
SELECT id, created_at, updated_at, reference FROM transactions WHERE id = $1
`

func (q *Queries) FindTransactionByID(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRow(ctx, findTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Reference,
	)
	return i, err
}

const findTransactionByReference = `-- name: FindTransactionByReference :one
SELECT id, created_at, updated_at, reference FROM transactions WHERE reference = $1
`

func (q *Queries) FindTransactionByReference(ctx context.Context, reference pgtype.Text) (Transaction, error) {
	row := q.db.QueryRow(ctx, findTransactionByReference, reference)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Reference,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, created_at, updated_at, reference FROM transactions
`

func (q *Queries) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Reference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions SET reference = $2 WHERE id = $1 RETURNING id, created_at, updated_at, reference
`

type UpdateTransactionParams struct {
	ID        int64       `db:"id"`
	Reference pgtype.Text `db:"reference"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction, arg.ID, arg.Reference)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Reference,
	)
	return i, err
}
