// Code generated by MockGen. DO NOT EDIT.
// Source: domain/transaction/repository.go
//
// Generated by this command:
//
//	mockgen -source=domain/transaction/repository.go -destination=domain/transaction/mock_repository.go -package=transaction
//

// Package transaction is a generated GoMock package.
package transaction

import (
	context "context"
	reflect "reflect"

	models "github.com/akeren/go-api-foundry/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateLedgerEntry mocks base method.
func (m *MockRepository) CreateLedgerEntry(ctx context.Context, entry *models.LedgerEntry) (*models.LedgerEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLedgerEntry", ctx, entry)
	ret0, _ := ret[0].(*models.LedgerEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLedgerEntry indicates an expected call of CreateLedgerEntry.
func (mr *MockRepositoryMockRecorder) CreateLedgerEntry(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLedgerEntry", reflect.TypeOf((*MockRepository)(nil).CreateLedgerEntry), ctx, entry)
}

// CreateTransaction mocks base method.
func (m *MockRepository) CreateTransaction(ctx context.Context, model *models.Transaction) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, model)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockRepositoryMockRecorder) CreateTransaction(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockRepository)(nil).CreateTransaction), ctx, model)
}

// FindAccountByID mocks base method.
func (m *MockRepository) FindAccountByID(ctx context.Context, accountID uint64) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAccountByID", ctx, accountID)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAccountByID indicates an expected call of FindAccountByID.
func (mr *MockRepositoryMockRecorder) FindAccountByID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAccountByID", reflect.TypeOf((*MockRepository)(nil).FindAccountByID), ctx, accountID)
}

// FindAccountByType mocks base method.
func (m *MockRepository) FindAccountByType(ctx context.Context, accountType string) (*models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAccountByType", ctx, accountType)
	ret0, _ := ret[0].(*models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAccountByType indicates an expected call of FindAccountByType.
func (mr *MockRepositoryMockRecorder) FindAccountByType(ctx, accountType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAccountByType", reflect.TypeOf((*MockRepository)(nil).FindAccountByType), ctx, accountType)
}

// FindTransactionByReference mocks base method.
func (m *MockRepository) FindTransactionByReference(ctx context.Context, reference string) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTransactionByReference", ctx, reference)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTransactionByReference indicates an expected call of FindTransactionByReference.
func (mr *MockRepositoryMockRecorder) FindTransactionByReference(ctx, reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTransactionByReference", reflect.TypeOf((*MockRepository)(nil).FindTransactionByReference), ctx, reference)
}

// GetBalance mocks base method.
func (m *MockRepository) GetBalance(ctx context.Context, accountID uint64) (*models.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, accountID)
	ret0, _ := ret[0].(*models.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockRepositoryMockRecorder) GetBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockRepository)(nil).GetBalance), ctx, accountID)
}

// GetLedgerEntries mocks base method.
func (m *MockRepository) GetLedgerEntries(ctx context.Context, accountID uint64) ([]*models.LedgerEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLedgerEntries", ctx, accountID)
	ret0, _ := ret[0].([]*models.LedgerEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLedgerEntries indicates an expected call of GetLedgerEntries.
func (mr *MockRepositoryMockRecorder) GetLedgerEntries(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLedgerEntries", reflect.TypeOf((*MockRepository)(nil).GetLedgerEntries), ctx, accountID)
}

// UpdateBalance mocks base method.
func (m *MockRepository) UpdateBalance(ctx context.Context, accountID uint64, amount int64) (*models.AccountBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalance", ctx, accountID, amount)
	ret0, _ := ret[0].(*models.AccountBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBalance indicates an expected call of UpdateBalance.
func (mr *MockRepositoryMockRecorder) UpdateBalance(ctx, accountID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalance", reflect.TypeOf((*MockRepository)(nil).UpdateBalance), ctx, accountID, amount)
}

// WithTx mocks base method.
func (m *MockRepository) WithTx(ctx context.Context, fn func(Repository) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryMockRecorder) WithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepository)(nil).WithTx), ctx, fn)
}
